version: "3.7"

services:
    api:
        build: ./api
        ports:
            - 7001:7001
        volumes:
            - ./api:/app
        env_file:
            - ./api/.env
    frontend:
        build: 
            context: ./frontend
            args: 
                - NODE_ENV=${NODE_ENV}
        ports:
            - 9001:9001
        volumes:
            - ./frontend:/code
