version: "3.7"

services:
    api:
        build: ./api
        ports:
            - 7002:7002
        volumes:
            - ./api:/app
        env_file:
            - ./api/.env
    frontend:
        build: 
            context: ./frontend
            args: 
                - NODE_ENV=${NODE_ENV}
        ports:
            - 9002:9002
        volumes:
            - ./frontend:/code
